version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/10badv'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'automated'

